### PR TITLE
Split hideHeaders preference into hideHeaders + hidePcbInfo; add options parsing.

### PR DESCRIPTION
**Pull request by szabodabo**

### CODE REVIEW

**Comment by trentks** [comment]
Hi @szabodabo,

I just realised that the README.md does not have any documentation as to what the original hideHeaders preference is supposed to do. Similarly, you have not added any documentation to the README.md for what this change is supposed to achieve.

Perhaps you can add some documentation for these two options?

Cheers.

**Comment by SchrodingersGat** [comment]
@szabodabo agreed with @trentks some doc info would not go astray here :) Are you happy to contribute this?

**Comment by szabodabo** [comment]
Sorry for the delay; added some doc info for these options. Happy to modify them if you'd like. Thanks for the quick review.

**Comment by SchrodingersGat** [comment]
Thanks @szabodabo I think this looks OK now. Thanks for your contribution

**Pull request merged**
