### PR TITLE
Made creation of backup file configurable

### PR DESCRIPTION
**Pull request by schneidersoft**

### CODE REVIEW

**Comment by schneidersoft** [comment]
This should also solve issue #14

**Comment by SchrodingersGat** [comment]
Hey @schneidersoft sorry this one got forgotten.

If you can fix the conflicts, I'll make sure it gets merged :)

**Comment by schneidersoft** [comment]
Have a look please

**Comment by SchrodingersGat** [comment]
Great, thanks for the contributions :)

**Pull request merged**
